name: Run Unit Test via Pytest  
  
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser selected to run tests"
        required: true
        type: choice
        options:
        - android
        - firefox
        - chromium
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v4  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser    
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    
      - name: Test with pytest  
        run: |
          echo "Browser: $BROWSER"
          coverage run -m pytest  -v -s
        env:
            BROWSER: ${{ inputs.browser || 'chromium' }}
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        if: always() # Always upload, even if tests fail
        with:
          name: test-report
          path: tests/reports/